project_name: opentelemetry-collector-releases
builds:
- id: googlemanagedprometheus
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - "386"
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: "386"
  - goos: windows
    goarch: arm64
  dir: distributions/googlemanagedprometheus/_build
  ldflags:
  - -s
  - -w
  flags:
  - -trimpath
  binary: googlemanagedprometheus
  env:
  - CGO_ENABLED=0
archives:
- id: googlemanagedprometheus
  builds:
  - googlemanagedprometheus
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
- package_name: googlemanagedprometheus
  contents:
  - src: distributions/googlemanagedprometheus/googlemanagedprometheus.service
    dst: /lib/systemd/system/googlemanagedprometheus.service
  - src: distributions/googlemanagedprometheus/googlemanagedprometheus.conf
    dst: /etc/googlemanagedprometheus/googlemanagedprometheus.conf
    type: config|noreplace
  - src: configs/googlemanagedprometheus.yaml
    dst: /etc/googlemanagedprometheus/config.yaml
    type: config
  scripts:
    preinstall: distributions/googlemanagedprometheus/preinstall.sh
    postinstall: distributions/googlemanagedprometheus/postinstall.sh
    preremove: distributions/googlemanagedprometheus/preremove.sh
  id: googlemanagedprometheus
  builds:
  - googlemanagedprometheus
  formats:
  - apk
  - deb
  - rpm
  maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
  description: OpenTelemetry Collector - googlemanagedprometheus
  license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
dockers:
- goos: linux
  goarch: "386"
  dockerfile: distributions/googlemanagedprometheus/Dockerfile
  image_templates:
  - otel/googlemanagedprometheus:{{ .Version }}-386
  - ghcr.io/open-telemetry/opentelemetry-collector-releases/googlemanagedprometheus:{{
    .Version }}-386
  extra_files:
  - configs/googlemanagedprometheus.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/386
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
- goos: linux
  goarch: amd64
  dockerfile: distributions/googlemanagedprometheus/Dockerfile
  image_templates:
  - otel/googlemanagedprometheus:{{ .Version }}-amd64
  - ghcr.io/open-telemetry/opentelemetry-collector-releases/googlemanagedprometheus:{{
    .Version }}-amd64
  extra_files:
  - configs/googlemanagedprometheus.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/amd64
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
- goos: linux
  goarch: arm64
  dockerfile: distributions/googlemanagedprometheus/Dockerfile
  image_templates:
  - otel/googlemanagedprometheus:{{ .Version }}-arm64
  - ghcr.io/open-telemetry/opentelemetry-collector-releases/googlemanagedprometheus:{{
    .Version }}-arm64
  extra_files:
  - configs/googlemanagedprometheus.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/arm64
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
docker_manifests:
- name_template: otel/googlemanagedprometheus:{{ .Version }}
  image_templates:
  - otel/googlemanagedprometheus:{{ .Version }}-386
  - otel/googlemanagedprometheus:{{ .Version }}-amd64
  - otel/googlemanagedprometheus:{{ .Version }}-arm64
- name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/googlemanagedprometheus:{{
    .Version }}
  image_templates:
  - ghcr.io/open-telemetry/opentelemetry-collector-releases/googlemanagedprometheus:{{
    .Version }}-386
  - ghcr.io/open-telemetry/opentelemetry-collector-releases/googlemanagedprometheus:{{
    .Version }}-amd64
  - ghcr.io/open-telemetry/opentelemetry-collector-releases/googlemanagedprometheus:{{
    .Version }}-arm64
